sudo: false
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  matrix:
   - django19
   - django110
   - django111
   - djangomaster

matrix:
  fast_finish: true
  include:
    - python: "3.4"
      env: flake8
  exclude:
    - python: "2.7"
      env: djangomaster
    - python: "3.6"
      env: django19
    - python: "3.6"
      env: django111
  allow_failures:
    - env: djangomaster

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install --upgrade pip wheel setuptools
  - pip install coveralls codacy-coverage tox-travis

script:
  - tox

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
